### ISSUE TITLE
v3.2.0 doesn't seem to have been published correctly

### ISSUE THREAD

**Issue by pruett** [umani/changed-files#9]
When using the new version (thanks for merging btw 🎉 ), I receive the following:
```
##[error]File not found: '/home/runner/work/_actions/futuratrepadeira/changed-files/v3.2.0/lib/main.js'
```

Inspecting the source code of the release [here](https://github.com/futuratrepadeira/changed-files/releases/tag/v3.2.0) it doesn't look like it was built correctly or the `lib` directory wasn't included.

**Comment by duarten** [comment]
Oh, sorry about that, I changed the way the action is deployed to match the current documented way of developing typescript actions, which uses a "dist" directory instead of "lib", but forgot to change `action.yml`. Fixing.

**Comment by duarten** [comment]
Should be fixed now. Could you please try again?

**Comment by pruett** [comment]
No worries, thanks for the quick action!

Still getting errors

```
Run futuratrepadeira/changed-files@v3.2.1
  with:
    repo-token: ***
    pattern: ^.*\.mdx$
    pr-number: 47
##[error]File not found: '/home/runner/work/_actions/futuratrepadeira/changed-files/v3.2.1/dist/main.js'
```

**Comment by pruett** [comment]
I *think* `npm run build && npm run pack` will properly build the `dist` directory. `git add dist` *should* fix the issue.

**Comment by duarten** [comment]
The issue was that in action.yml I had lib/main.js, then I changed to dist/main.js but it should have been dist/index.js.

Long story short, it should be fixed now :) I kept the same release number so you can just re-run your workflow to try it again.

**Comment by pruett** [comment]
Ah, I see.

**Comment by pruett** [comment]
Hrm...

Just got the following

```
Run futuratrepadeira/changed-files@v3.2.1
##[error]File not found: '/home/runner/work/_actions/futuratrepadeira/changed-files/v3.2.1/dist/index.js'
```

**Comment by pruett** [comment]
Doesn't look like `dist` directory is being included in the release source code. Just want to double check that you've added the `dist` dir to source control.

**Comment by duarten** [comment]
I did: https://github.com/futuratrepadeira/changed-files/tree/releases/v3/dist

Right now I have no idea what could be missing. Maybe it had something to do with me using the same version number for the new release? In that case, it should work if you use it as `changed-files@releases/v3`.

**Comment by pruett** [comment]
Thanks for looking into this!

It looks like it's perhaps a misaligned tag, as the `v3.2.1` tag points to source code without a `dist` directory as seen here https://github.com/futuratrepadeira/changed-files/tree/v3.2.1

**Comment by pruett** [comment]
Also, for what it's worth...I cut a release on a personal fork and the new `pr-number` input seems to be working well! 👍

**Comment by duarten** [comment]
Good to know! :) 

I fixed the tag, I think for good!

**Comment by duarten** [comment]
Good to know! :) 

I fixed the tag, I think for good!

**Comment by duarten** [comment]
Good to know! :) 

I fixed the tag, I think for good!

**Comment by pruett** [comment]
Sorry it's taken me awhile to get back to this! Thanks for all the work in getting this released!

I would suggest, however, that you create a `v3` tag and update it throughout patches and fixed as suggest here https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#recommendations in order for people to bind to the latest major fixes, such as `futuratrepadeira/changed-files@v3`

Looks like you handled it this way with `v1` and `v2`.

Thanks again.

**Comment by duarten** [comment]
That makes a lot of sense, thanks for the suggestion. I created the `v3` tag :)
